// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsjasmzgznsxqmnwedux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzamFzbXpnem5zeHFtbndlZHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDAxNjUsImV4cCI6MjA3NDgxNjE2NX0.yV-pRZJB6-Cz12fLVnmVpGAf2V4ZJvU7tXeGTN35X60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});