// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsrlsokoazgoqjvbucoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzcmxzb2tvYXpnb3FqdmJ1Y29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTQzNTIsImV4cCI6MjA3Mjk3MDM1Mn0.hgYHseriE1Bh9QcID9MuIHZmubaiVXKUxvc4xnvzk1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});